openapi: 3.1.0
info:
  title: PartnerAPI - Links Endpoints
  version: 1.0.0
servers:
  - url: https://partner.prizma.tools
    description: Base URL for all API requests
paths:
  /links:
    post:
      tags:
      - links
      summary: Create Invite Link
      operationId: create_invite_link_links_post
      security:
      - HTTPBearer: []
      parameters:
      - name: external_id
        in: query
        required: true
        schema:
          type: integer
          title: External Id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InviteLinkCreateDTO'
      responses:
        '201':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InviteLinkResponseDTO'
        '400':
          content:
            application/json:
              example:
                detail: Partner title incorrect or does not exist
              schema:
                $ref: '#/components/schemas/ErrorSchema'
          description: Bad Request
        '401':
          content:
            application/json:
              example:
                detail: Account doesn't exist
              schema:
                $ref: '#/components/schemas/ErrorSchema'
          description: Unauthorized
        '403':
          content:
            application/json:
              examples:
                bot_have_not_rights:
                  summary: У бота нет прав
                  value:
                    detail: У бота нет прав на выполнение данной операции в канале
                      -1009410
                dont_have_access_to_channel:
                  summary: Нет доступа к каналу
                  value:
                    detail: У пользователя нет доступа к данному каналу
              schema:
                $ref: '#/components/schemas/ErrorSchema'
          description: Forbidden
        '404':
          content:
            application/json:
              examples:
                partner_not_found:
                  summary: Партнер не найден
                  value:
                    detail: Partner with id=123 not found
              schema:
                $ref: '#/components/schemas/ErrorSchema'
          description: Not Found
        '409':
          content:
            application/json:
              example:
                detail: Бот с helper не добавлен в канал -1009410
              schema:
                $ref: '#/components/schemas/ErrorSchema'
          description: Conflict
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /links/all:
    post:
      tags:
      - links
      summary: Get All Links
      operationId: get_all_links_links_all_post
      security:
      - HTTPBearer: []
      parameters:
      - name: external_id
        in: query
        required: true
        schema:
          type: integer
          title: External Id
      - name: channel_id
        in: query
        required: true
        schema:
          type: integer
          title: Channel Id
      - name: page
        in: query
        required: false
        schema:
          type: integer
          default: 1
          title: Page
      - name: limit
        in: query
        required: false
        schema:
          type: integer
          default: 10
          title: Limit
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AllInviteLinksResponseDTO'
        '400':
          content:
            application/json:
              example:
                detail: Partner title incorrect or does not exist
              schema:
                $ref: '#/components/schemas/ErrorSchema'
          description: Bad Request
        '401':
          content:
            application/json:
              example:
                detail: Account doesn't exist
              schema:
                $ref: '#/components/schemas/ErrorSchema'
          description: Unauthorized
        '403':
          content:
            application/json:
              examples:
                bot_have_not_rights:
                  summary: У бота нет прав
                  value:
                    detail: У бота нет прав на выполнение данной операции в канале
                      -1009410
                dont_have_access_to_channel:
                  summary: Нет доступа к каналу
                  value:
                    detail: У пользователя нет доступа к данному каналу
              schema:
                $ref: '#/components/schemas/ErrorSchema'
          description: Forbidden
        '404':
          content:
            application/json:
              examples:
                partner_not_found:
                  summary: Партнер не найден
                  value:
                    detail: Partner with id=123 not found
              schema:
                $ref: '#/components/schemas/ErrorSchema'
          description: Not Found
        '409':
          content:
            application/json:
              example:
                detail: Бот с helper не добавлен в канал -1009410
              schema:
                $ref: '#/components/schemas/ErrorSchema'
          description: Conflict
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  securitySchemes:
    HTTPBearer:
      type: http
      scheme: bearer
  schemas:
    AllInviteLinksResponseDTO:
      properties:
        page:
          type: integer
          title: Page
        limit:
          type: integer
          title: Limit
        total:
          type: integer
          title: Total
        items:
          items:
            $ref: '#/components/schemas/InviteLinkResponseDTO'
          type: array
          title: Items
      type: object
      required:
      - page
      - limit
      - total
      - items
      title: AllInviteLinksResponseDTO
    TagInInviteLinkDTO:
      properties:
        id:
          type: string
          format: uuid
          title: Id
        name:
          type: string
          title: Name
        color:
          type: string
          title: Color
        type:
          $ref: '#/components/schemas/TagTypeDTO'
      type: object
      required:
      - id
      - name
      - color
      - type
      title: TagInInviteLinkDTO
    ErrorSchema:
      properties:
        detail:
          type: string
          title: Detail
      type: object
      required:
      - detail
      title: ErrorSchema
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    InviteLinkCreateDTO:
      properties:
        channel_id:
          type: integer
          title: Channel Id
        name:
          type: string
          title: Name
        creates_join_request:
          type: boolean
          title: Creates Join Request
          default: false
        expire_date:
          anyOf:
          - type: string
            format: date-time
          - type: 'null'
          title: Expire Date
        member_limit:
          anyOf:
          - type: integer
          - type: 'null'
          title: Member Limit
      type: object
      required:
      - channel_id
      - name
      title: InviteLinkCreateDTO
    TagTypeDTO:
      properties:
        id:
          type: string
          format: uuid
          title: Id
        name:
          type: string
          title: Name
      type: object
      required:
      - id
      - name
      title: TagTypeDTO
    InviteLinkResponseDTO:
      properties:
        id:
          type: string
          title: Id
        name:
          anyOf:
          - type: string
          - type: 'null'
          title: Name
        channel_id:
          type: integer
          title: Channel Id
        invite_link:
          type: string
          title: Invite Link
        creates_join_request:
          type: boolean
          title: Creates Join Request
        expire_date:
          anyOf:
          - type: string
            format: date-time
          - type: 'null'
          title: Expire Date
        member_limit:
          anyOf:
          - type: integer
          - type: 'null'
          title: Member Limit
        created_at:
          type: string
          format: date-time
          title: Created At
        updated_at:
          anyOf:
          - type: string
            format: date-time
          - type: 'null'
          title: Updated At
        is_bot_created:
          type: boolean
          title: Is Bot Created
        creator_id:
          anyOf:
          - type: integer
          - type: 'null'
          title: Creator Id
        budget:
          type: number
          title: Budget
        tags:
          items:
            $ref: '#/components/schemas/TagInInviteLinkDTO'
          type: array
          title: Tags
      type: object
      required:
      - id
      - channel_id
      - invite_link
      - creates_join_request
      - created_at
      - is_bot_created
      - budget
      title: InviteLinkResponseDTO
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
